[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

