[phases.setup]
# Ставим Python и ffmpeg (pip подтянем внутри виртуалки)
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
# Создаём своё виртуальное окружение и ставим туда pip + зависимости
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
# ВЫБЕРИ один вариант запуска:

# 1) Если запускаешь облачную, быструю версию на Deepgram:
cmd = "/opt/venv/bin/python bot_cloud.py"

# 2) Если запускаешь локальный Whisper (медленнее):
# cmd = "/opt/venv/bin/python bot.py"




