[phases.setup]
# Ставим Python, сам pip как пакет и ffmpeg
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
# Используем pip из Python — так надёжнее на Nix
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
# Если запускаешь локальную версию — оставь bot.py
# cmd = "python bot.py"

# Если запускаешь облачную быструю версию (Deepgram) — раскомментируй эту строку:
cmd = "python bot_cloud.py"



