[phases.setup]
# Явно ставим Python и ffmpeg
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
# Важно: вызываем pip через python, тогда он точно найдётся
cmds = ["python -m pip install --no-cache-dir -r requirements.txt"]

[start]
# Если сейчас в репо главный файл называется bot.py — оставляем так:
cmd = "python bot.py"


