[phases.setup]
# Ставим Python и ffmpeg
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
# Создаём своё виртуальное окружение и ставим зависимости в него
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
# Запускаем ТВОЙ файл bot.py
cmd = "/opt/venv/bin/python bot.py"





