[phases.setup]
# Ставим полную сборку Python (включает ensurepip) и ffmpeg
nixPkgs = ["python311Full", "ffmpeg"]

[phases.install]
# Явно разворачиваем pip и ставим зависимости
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
# Если у тебя запускается bot.py — оставь так:
cmd = "python bot.py"
# Если запускаешь облачную версию — поменяй на:
# cmd = "python bot_cloud.py"



