[phases.setup]
# Ставим Python и ffmpeg
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
# Делаем свою виртуалку и ставим зависимости в неё
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
# Запускаем быструю облачную версию
cmd = "/opt/venv/bin/python bot_cloud.py"





